### PR TITLE
Frr ospf vrf

### PR DESCRIPTION
**Pull request by pguibert6WIND**
This test ensures non regression against a simple ospf case where a VRF backend is netns.

### CODE REVIEW

**Comment by pguibert6WIND** [comment]
Hi @rzalamena ,

do you mind if you can do a review on that pull request , please ?
thanks

**Comment by rzalamena** [comment]
@pguibert6WIND please don't include modifications from other PRs (always start forking from `master`). I can see a lot of things I pointed out here: https://github.com/FRRouting/topotests/pull/65

**Comment by pguibert6WIND** [comment]
Hi @rzalamena ,
I simplified, and I made the requested changes. please review.

**Comment by rzalamena** [comment]
> Hi @rzalamena ,
> #65 is yet included in #72.
>
> this is because 72 relies on 65. and I don't want to create a new pull request.
>
> it is up to you to:
>
> either review first pr 65, then pr 72
> or only pr 72 ( I renamed the title of this pr)

Fair enough, then I'll review PR #65 first.

**Comment by pguibert6WIND** [comment]
should be relaunched when https://github.com/FRRouting/frr/pull/1818 is merged

**Comment by pguibert6WIND** [comment]
I don't get why errors appear  in this test ( extracted errors are https://github.com/FRRouting/topotests/issues/106), and bgp_vrf test passes OK

**Comment by pguibert6WIND** [comment]
Hi @rzalamena , can you help me in relaunching tests for this pr please
it looks like the arm8 crash is due to bgp ecmp, and not this pr.

thanks
```
build	24-Jul-2018 09:27:25	2018-07-24 16:27:25,989 INFO: r1: waiting for daemons stopping (2 seconds)
error	24-Jul-2018 09:27:29	
error	24-Jul-2018 09:27:29	r1: zebra crashed. Core file found - Backtrace follows:
error	24-Jul-2018 09:27:29	[New LWP 20857]
error	24-Jul-2018 09:27:29	[New LWP 20836]
error	24-Jul-2018 09:27:29	[New LWP 20858]
error	24-Jul-2018 09:27:29	[Thread debugging using libthread_db enabled]
error	24-Jul-2018 09:27:29	Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
error	24-Jul-2018 09:27:29	Core was generated by `/usr/lib/frr/zebra'.
error	24-Jul-2018 09:27:29	Program terminated with signal SIGABRT, Aborted.
error	24-Jul-2018 09:27:29	#0  0x0000ffffb874b528 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	24-Jul-2018 09:27:29	[Current thread is 1 (Thread 0xffffb8341090 (LWP 20857))]
error	24-Jul-2018 09:27:29	#0  0x0000ffffb874b528 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	24-Jul-2018 09:27:29	#1  0x0000ffffb874c9e0 in __GI_abort () at abort.c:89
error	24-Jul-2018 09:27:29	#2  0x0000ffffb88f9b70 in core_handler (signo=11, siginfo=0xffffb833f100, context=<optimized out>) at lib/sigevent.c:247
error	24-Jul-2018 09:27:29	#3  <signal handler called>
error	24-Jul-2018 09:27:29	#4  __GI___pthread_mutex_lock (mutex=mutex@entry=0x6601010a) at pthread_mutex_lock.c:67
error	24-Jul-2018 09:27:29	#5  0x0000ffffb8905f58 in funcname_thread_add_read_write (dir=dir@entry=0, m=0x6601000a, func=func@entry=0xaaaadb22a260 <zserv_read>, arg=0xffffb8340628, arg@entry=0xaaab03365870, fd=53903024, t_ptr=t_ptr@entry=0xaaab03365908, funcname=funcname@entry=0xaaaadb24ccf8 "zserv_read", schedfrom=schedfrom@entry=0xaaaadb24cce8 "zebra/zserv.c", fromln=fromln@entry=451) at lib/thread.c:785
error	24-Jul-2018 09:27:29	#6  0x0000aaaadb229558 in zserv_client_event (client=client@entry=0xaaab03365870, event=ZSERV_CLIENT_READ) at zebra/zserv.c:450
error	24-Jul-2018 09:27:29	#7  0x0000aaaadb22a40c in zserv_client_event (event=ZSERV_CLIENT_READ, client=0xaaab03365870) at zebra/zserv.c:429
error	24-Jul-2018 09:27:29	#8  zserv_read (thread=<optimized out>) at zebra/zserv.c:433
error	24-Jul-2018 09:27:29	#9  0x0000ffffb8906de0 in thread_call (thread=thread@entry=0xffffb83407c0) at lib/thread.c:1576
error	24-Jul-2018 09:27:29	#10 0x0000ffffb88d8220 in fpt_run (arg=0xaaab033679b0) at lib/frr_pthread.c:293
error	24-Jul-2018 09:27:29	#11 0x0000ffffb8867fc4 in start_thread (arg=0xffffb88d8128 <fpt_run>) at pthread_create.c:335
error	24-Jul-2018 09:27:29	#12 0x0000ffffb87e02e0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89
error	24-Jul-2018 09:27:29	2018-07-24 16:27:29,305 ERROR: assert failed at "test_bgp_ecmp_topo1/test_bgp_ecmp": 
error	24-Jul-2018 09:27:29	r1: zebra crashed. Core file found - Backtrace follows:
error	24-Jul-2018 09:27:29	[New LWP 20857]
error	24-Jul-2018 09:27:29	[New LWP 20836]
error	24-Jul-2018 09:27:29	[New LWP 20858]
error	24-Jul-2018 09:27:29	[Thread debugging using libthread_db enabled]
error	24-Jul-2018 09:27:29	Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
error	24-Jul-2018 09:27:29	Core was generated by `/usr/lib/frr/zebra'.
error	24-Jul-2018 09:27:29	Program terminated with signal SIGABRT, Aborted.
error	24-Jul-2018 09:27:29	#0  0x0000ffffb874b528 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	24-Jul-2018 09:27:29	[Current thread is 1 (Thread 0xffffb8341090 (LWP 20857))]
error	24-Jul-2018 09:27:29	#0  0x0000ffffb874b528 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	24-Jul-2018 09:27:29	#1  0x0000ffffb874c9e0 in __GI_abort () at abort.c:89
error	24-Jul-2018 09:27:29	#2  0x0000ffffb88f9b70 in core_handler (signo=11, siginfo=0xffffb833f100, context=<optimized out>) at lib/sigevent.c:247
error	24-Jul-2018 09:27:29	#3  <signal handler called>
error	24-Jul-2018 09:27:29	#4  __GI___pthread_mutex_lock (mutex=mutex@entry=0x6601010a) at pthread_mutex_lock.c:67
error	24-Jul-2018 09:27:29	#5  0x0000ffffb8905f58 in funcname_thread_add_read_write (dir=dir@entry=0, m=0x6601000a, func=func@entry=0xaaaadb22a260 <zserv_read>, arg=0xffffb8340628, arg@entry=0xaaab03365870, fd=53903024, t_ptr=t_ptr@entry=0xaaab03365908, funcname=funcname@entry=0xaaaadb24ccf8 "zserv_read", schedfrom=schedfrom@entry=0xaaaadb24cce8 "zebra/zserv.c", fromln=fromln@entry=451) at lib/thread.c:785
error	24-Jul-2018 09:27:29	#6  0x0000aaaadb229558 in zserv_client_event (client=client@entry=0xaaab03365870, event=ZSERV_CLIENT_READ) at zebra/zserv.c:450
error	24-Jul-2018 09:27:29	#7  0x0000aaaadb22a40c in zserv_client_event (event=ZSERV_CLIENT_READ, client=0xaaab03365870) at zebra/zserv.c:429
error	24-Jul-2018 09:27:29	#8  zserv_read (thread=<optimized out>) at zebra/zserv.c:433
error	24-Jul-2018 09:27:29	#9  0x0000ffffb8906de0 in thread_call (thread=thread@entry=0xffffb83407c0) at lib/thread.c:1576
error	24-Jul-2018 09:27:29	#10 0x0000ffffb88d8220 in fpt_run (arg=0xaaab033679b0) at lib/frr_pthread.c:293
error	24-Jul-2018 09:27:29	#11 0x0000ffffb8867fc4 in start_thread (arg=0xffffb88d8128 <fpt_run>) at pthread_create.c:335
error	24-Jul-2018 09:27:29	#12 0x0000ffffb87e02e0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89
error	24-Jul-2018 09:27:29	
build	24-Jul-2018 09:27:29	
build	24-Jul-2018 09:27:29	bgp-ecmp-topo1/test_bgp_ecmp_topo1.py::test_bgp_ecmp ERROR
```

**Comment by rzalamena** [comment]
I just checked the log output for the last run and it seems that this test is broken on FRR 5.0:

```
build	25-Jul-2018 00:05:16	ospf-topo1-vrf/test_ospf_topo1_vrf.py::test_memory_leak 2018-07-25 09:05:16,290 INFO: r1: stopping ospfd
build	25-Jul-2018 00:05:16	2018-07-25 09:05:16,297 INFO: r1: stopping zebra
build	25-Jul-2018 00:05:16	2018-07-25 09:05:16,298 INFO: r1: waiting for daemons stopping (2 seconds)
error	25-Jul-2018 00:05:18	
error	25-Jul-2018 00:05:18	r1: zebra crashed. Core file found - Backtrace follows:
error	25-Jul-2018 00:05:18	[New LWP 14196]
error	25-Jul-2018 00:05:18	[Thread debugging using libthread_db enabled]
error	25-Jul-2018 00:05:18	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
error	25-Jul-2018 00:05:18	Core was generated by `/usr/lib/frr/zebra --vrfwnetns'.
error	25-Jul-2018 00:05:18	Program terminated with signal SIGABRT, Aborted.
error	25-Jul-2018 00:05:18	#0  0x00007f791077a428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	25-Jul-2018 00:05:18	#0  0x00007f791077a428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	25-Jul-2018 00:05:18	#1  0x00007f791077c02a in __GI_abort () at abort.c:89
error	25-Jul-2018 00:05:18	#2  0x00007f7911190c8a in core_handler (signo=11, siginfo=0x7fff6af70af0, context=0x7fff6af709c0) at lib/sigevent.c:249
error	25-Jul-2018 00:05:18	#3  <signal handler called>
error	25-Jul-2018 00:05:18	#4  hash_clean (hash=0x0, free_func=0x55b3fe32ad30 <zebra_pbr_rules_free>) at lib/hash.c:298
error	25-Jul-2018 00:05:18	#5  0x000055b3fe329e22 in zebra_ns_disable (ns_id=<optimized out>, info=info@entry=0x7fff6af70ff0) at zebra/zebra_ns.c:263
error	25-Jul-2018 00:05:18	#6  0x000055b3fe329f92 in zebra_ns_disabled (ns=0x55b40031d990) at zebra/zebra_ns.c:129
error	25-Jul-2018 00:05:18	#7  0x00007f791117f18e in ns_walk_func (func=0x55b3fe329f50 <zebra_ns_disabled>) at lib/netns_linux.c:385
error	25-Jul-2018 00:05:18	#8  0x000055b3fe318ece in sigint () at zebra/main.c:148
error	25-Jul-2018 00:05:18	#9  0x00007f7911190d28 in quagga_sigevent_process () at lib/sigevent.c:103
error	25-Jul-2018 00:05:18	#10 0x00007f791119d22d in thread_fetch (m=m@entry=0x55b4002185d0, fetch=fetch@entry=0x7fff6af71190) at lib/thread.c:1359
error	25-Jul-2018 00:05:18	#11 0x00007f79111790f3 in frr_run (master=0x55b4002185d0) at lib/libfrr.c:878
error	25-Jul-2018 00:05:18	#12 0x000055b3fe30c0f2 in main (argc=2, argv=0x7fff6af71478) at zebra/main.c:379
build	25-Jul-2018 00:05:18	2018-07-25 09:05:18,728 INFO: 
build	25-Jul-2018 00:05:18	Router r1 zebra StdErr Log:
build	25-Jul-2018 00:05:18	2018/07/25 09:03:39 errors: ZEBRA: Can not enable NS 1: Permission denied!
build	25-Jul-2018 00:05:18	2018/07/25 09:03:39 warnings: ZEBRA: Can not associate NS 1 with NETNS /run/netns/r3-cust1
build	25-Jul-2018 00:05:18	2018/07/25 09:03:39 warnings: ZEBRA: NS notify : failed to create NS /run/netns/r3-cust1
build	25-Jul-2018 00:05:18	2018/07/25 09:03:39 errors: ZEBRA: Can not enable NS 2: Permission denied!
build	25-Jul-2018 00:05:18	2018/07/25 09:03:39 warnings: ZEBRA: Can not associate NS 2 with NETNS /run/netns/r2-cust1
build	25-Jul-2018 00:05:18	2018/07/25 09:03:39 warnings: ZEBRA: NS notify : failed to create NS /run/netns/r2-cust1
build	25-Jul-2018 00:05:18	core_handler: showing active allocations in memory group libfrr
build	25-Jul-2018 00:05:18	core_handler: memstats:  Host config                   :      4 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Command Tokens                :   3375 *         72
build	25-Jul-2018 00:05:18	core_handler: memstats:  Command Token Text            :   2510 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Command Token Help            :   2510 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Command Argument Name         :    620 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Graph                         :     23 *          8
build	25-Jul-2018 00:05:18	core_handler: memstats:  Graph Node                    :   3972 *         32
build	25-Jul-2018 00:05:18	core_handler: memstats:  Hash                          :     98 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Hash Bucket                   :    609 *         32
build	25-Jul-2018 00:05:18	core_handler: memstats:  Hash Index                    :     49 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Hook entry                    :     13 *         48
build	25-Jul-2018 00:05:18	core_handler: memstats:  Link List                     :     13 *         40
build	25-Jul-2018 00:05:18	core_handler: memstats:  Link Node                     :     59 *         24
build	25-Jul-2018 00:05:18	core_handler: memstats:  Logging                       :      2 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Temporary memory              :      1 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  NetNS Context                 :      8 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  NetNS Name                    :      4 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Priority queue                :      1 *         32
build	25-Jul-2018 00:05:18	core_handler: memstats:  Priority queue data           :      1 *        256
build	25-Jul-2018 00:05:18	core_handler: memstats:  Privilege information         :      2 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Stream                        :      3 *         40
build	25-Jul-2018 00:05:18	core_handler: memstats:  Stream data                   :      3 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Route table                   :      4 *         48
build	25-Jul-2018 00:05:18	core_handler: memstats:  Thread                        :     17 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Thread master                 :      3 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Thread stats                  :     12 *         64
build	25-Jul-2018 00:05:18	core_handler: memstats:  Vector                        :   7995 *         16
build	25-Jul-2018 00:05:18	core_handler: memstats:  Vector index                  :   7995 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Work queue                    :      2 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: memstats:  Work queue item               :      1 *         24
build	25-Jul-2018 00:05:18	core_handler: memstats:  Work queue name string        :      1 * (variably sized)
build	25-Jul-2018 00:05:18	core_handler: showing active allocations in memory group Label Manager
build	25-Jul-2018 00:05:18	core_handler: showing active allocations in memory group zebra
build	25-Jul-2018 00:05:18	core_handler: memstats:  Zebra Name Space              :      4 *        312
build	25-Jul-2018 00:05:18	core_handler: showing active allocations in memory group Table Manager
build	25-Jul-2018 00:05:18	
build	25-Jul-2018 00:05:18	2018-07-25 09:05:18,734 INFO: r2: stopping ospfd
build	25-Jul-2018 00:05:18	2018-07-25 09:05:18,739 INFO: r2: stopping zebra
build	25-Jul-2018 00:05:18	2018-07-25 09:05:18,739 INFO: r2: waiting for daemons stopping (2 seconds)
error	25-Jul-2018 00:05:21	
error	25-Jul-2018 00:05:21	r2: zebra crashed. Core file found - Backtrace follows:
error	25-Jul-2018 00:05:21	[New LWP 14228]
error	25-Jul-2018 00:05:21	[Thread debugging using libthread_db enabled]
error	25-Jul-2018 00:05:21	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
error	25-Jul-2018 00:05:21	Core was generated by `/usr/lib/frr/zebra --vrfwnetns'.
error	25-Jul-2018 00:05:21	Program terminated with signal SIGABRT, Aborted.
error	25-Jul-2018 00:05:21	#0  0x00007f2d6a47f428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	25-Jul-2018 00:05:21	#0  0x00007f2d6a47f428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	25-Jul-2018 00:05:21	#1  0x00007f2d6a48102a in __GI_abort () at abort.c:89
error	25-Jul-2018 00:05:21	#2  0x00007f2d6ae95c8a in core_handler (signo=11, siginfo=0x7ffd141e83f0, context=0x7ffd141e82c0) at lib/sigevent.c:249
error	25-Jul-2018 00:05:21	#3  <signal handler called>
error	25-Jul-2018 00:05:21	#4  hash_clean (hash=0x0, free_func=0x559ba94b3d30 <zebra_pbr_rules_free>) at lib/hash.c:298
error	25-Jul-2018 00:05:21	#5  0x0000559ba94b2e22 in zebra_ns_disable (ns_id=<optimized out>, info=info@entry=0x7ffd141e88d0) at zebra/zebra_ns.c:263
error	25-Jul-2018 00:05:21	#6  0x0000559ba94b2f92 in zebra_ns_disabled (ns=0x559baaac5990) at zebra/zebra_ns.c:129
error	25-Jul-2018 00:05:21	#7  0x00007f2d6ae8418e in ns_walk_func (func=0x559ba94b2f50 <zebra_ns_disabled>) at lib/netns_linux.c:385
error	25-Jul-2018 00:05:21	#8  0x0000559ba94a1ece in sigint () at zebra/main.c:148
error	25-Jul-2018 00:05:21	#9  0x00007f2d6ae95d28 in quagga_sigevent_process () at lib/sigevent.c:103
error	25-Jul-2018 00:05:21	#10 0x00007f2d6aea222d in thread_fetch (m=m@entry=0x559baa9c05d0, fetch=fetch@entry=0x7ffd141e8a70) at lib/thread.c:1359
error	25-Jul-2018 00:05:21	#11 0x00007f2d6ae7e0f3 in frr_run (master=0x559baa9c05d0) at lib/libfrr.c:878
error	25-Jul-2018 00:05:21	#12 0x0000559ba94950f2 in main (argc=2, argv=0x7ffd141e8d58) at zebra/main.c:379
build	25-Jul-2018 00:05:21	2018-07-25 09:05:21,188 INFO: 
build	25-Jul-2018 00:05:21	Router r2 zebra StdErr Log:
build	25-Jul-2018 00:05:21	2018/07/25 09:03:40 errors: ZEBRA: Can not enable NS 1: Permission denied!
build	25-Jul-2018 00:05:21	2018/07/25 09:03:40 warnings: ZEBRA: Can not associate NS 1 with NETNS /run/netns/r3-cust1
build	25-Jul-2018 00:05:21	2018/07/25 09:03:40 warnings: ZEBRA: NS notify : failed to create NS /run/netns/r3-cust1
build	25-Jul-2018 00:05:21	2018/07/25 09:03:40 errors: ZEBRA: Can not enable NS 3: Permission denied!
build	25-Jul-2018 00:05:21	2018/07/25 09:03:40 warnings: ZEBRA: Can not associate NS 3 with NETNS /run/netns/r1-cust1
build	25-Jul-2018 00:05:21	2018/07/25 09:03:40 warnings: ZEBRA: NS notify : failed to create NS /run/netns/r1-cust1
build	25-Jul-2018 00:05:21	core_handler: showing active allocations in memory group libfrr
build	25-Jul-2018 00:05:21	core_handler: memstats:  Host config                   :      4 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Command Tokens                :   3375 *         72
build	25-Jul-2018 00:05:21	core_handler: memstats:  Command Token Text            :   2510 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Command Token Help            :   2510 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Command Argument Name         :    620 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Graph                         :     23 *          8
build	25-Jul-2018 00:05:21	core_handler: memstats:  Graph Node                    :   3972 *         32
build	25-Jul-2018 00:05:21	core_handler: memstats:  Hash                          :     98 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Hash Bucket                   :    609 *         32
build	25-Jul-2018 00:05:21	core_handler: memstats:  Hash Index                    :     49 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Hook entry                    :     13 *         48
build	25-Jul-2018 00:05:21	core_handler: memstats:  Link List                     :     13 *         40
build	25-Jul-2018 00:05:21	core_handler: memstats:  Link Node                     :     59 *         24
build	25-Jul-2018 00:05:21	core_handler: memstats:  Logging                       :      2 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Temporary memory              :      1 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  NetNS Context                 :      8 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  NetNS Name                    :      4 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Priority queue                :      1 *         32
build	25-Jul-2018 00:05:21	core_handler: memstats:  Priority queue data           :      1 *        256
build	25-Jul-2018 00:05:21	core_handler: memstats:  Privilege information         :      2 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Stream                        :      3 *         40
build	25-Jul-2018 00:05:21	core_handler: memstats:  Stream data                   :      3 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Route table                   :      4 *         48
build	25-Jul-2018 00:05:21	core_handler: memstats:  Thread                        :     16 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Thread master                 :      3 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Thread stats                  :     12 *         64
build	25-Jul-2018 00:05:21	core_handler: memstats:  Vector                        :   7995 *         16
build	25-Jul-2018 00:05:21	core_handler: memstats:  Vector index                  :   7995 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Work queue                    :      2 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: memstats:  Work queue item               :      1 *         24
build	25-Jul-2018 00:05:21	core_handler: memstats:  Work queue name string        :      1 * (variably sized)
build	25-Jul-2018 00:05:21	core_handler: showing active allocations in memory group Label Manager
build	25-Jul-2018 00:05:21	core_handler: showing active allocations in memory group zebra
build	25-Jul-2018 00:05:21	core_handler: memstats:  Zebra Name Space              :      4 *        312
build	25-Jul-2018 00:05:21	core_handler: showing active allocations in memory group Table Manager
build	25-Jul-2018 00:05:21	
build	25-Jul-2018 00:05:21	2018-07-25 09:05:21,192 INFO: r3: stopping ospfd
build	25-Jul-2018 00:05:21	2018-07-25 09:05:21,197 INFO: r3: stopping zebra
build	25-Jul-2018 00:05:21	2018-07-25 09:05:21,202 INFO: r3: waiting for daemons stopping (2 seconds)
error	25-Jul-2018 00:05:23	
error	25-Jul-2018 00:05:23	r3: zebra crashed. Core file found - Backtrace follows:
error	25-Jul-2018 00:05:23	[New LWP 14262]
error	25-Jul-2018 00:05:23	[Thread debugging using libthread_db enabled]
error	25-Jul-2018 00:05:23	Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
error	25-Jul-2018 00:05:23	Core was generated by `/usr/lib/frr/zebra --vrfwnetns'.
error	25-Jul-2018 00:05:23	Program terminated with signal SIGABRT, Aborted.
error	25-Jul-2018 00:05:23	#0  0x00007fc4fefc8428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	25-Jul-2018 00:05:23	#0  0x00007fc4fefc8428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
error	25-Jul-2018 00:05:23	#1  0x00007fc4fefca02a in __GI_abort () at abort.c:89
error	25-Jul-2018 00:05:23	#2  0x00007fc4ff9dec8a in core_handler (signo=11, siginfo=0x7ffc19a37ff0, context=0x7ffc19a37ec0) at lib/sigevent.c:249
error	25-Jul-2018 00:05:23	#3  <signal handler called>
error	25-Jul-2018 00:05:23	#4  hash_clean (hash=0x0, free_func=0x559a94f52d30 <zebra_pbr_rules_free>) at lib/hash.c:298
error	25-Jul-2018 00:05:23	#5  0x0000559a94f51e22 in zebra_ns_disable (ns_id=<optimized out>, info=info@entry=0x7ffc19a38500) at zebra/zebra_ns.c:263
error	25-Jul-2018 00:05:23	#6  0x0000559a94f51f92 in zebra_ns_disabled (ns=0x559a972a70b0) at zebra/zebra_ns.c:129
error	25-Jul-2018 00:05:23	#7  0x00007fc4ff9cd18e in ns_walk_func (func=0x559a94f51f50 <zebra_ns_disabled>) at lib/netns_linux.c:385
error	25-Jul-2018 00:05:23	#8  0x0000559a94f40ece in sigint () at zebra/main.c:148
error	25-Jul-2018 00:05:23	#9  0x00007fc4ff9ded28 in quagga_sigevent_process () at lib/sigevent.c:103
error	25-Jul-2018 00:05:23	#10 0x00007fc4ff9eb22d in thread_fetch (m=m@entry=0x559a971935d0, fetch=fetch@entry=0x7ffc19a386a0) at lib/thread.c:1359
error	25-Jul-2018 00:05:23	#11 0x00007fc4ff9c70f3 in frr_run (master=0x559a971935d0) at lib/libfrr.c:878
error	25-Jul-2018 00:05:23	#12 0x0000559a94f340f2 in main (argc=2, argv=0x7ffc19a38988) at zebra/main.c:379
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,581 INFO: 
build	25-Jul-2018 00:05:23	Router r3 zebra StdErr Log:
build	25-Jul-2018 00:05:23	2018/07/25 09:03:41 errors: ZEBRA: Can not enable NS 2: Permission denied!
build	25-Jul-2018 00:05:23	2018/07/25 09:03:41 warnings: ZEBRA: Can not associate NS 2 with NETNS /run/netns/r2-cust1
build	25-Jul-2018 00:05:23	2018/07/25 09:03:41 warnings: ZEBRA: NS notify : failed to create NS /run/netns/r2-cust1
build	25-Jul-2018 00:05:23	2018/07/25 09:03:41 errors: ZEBRA: Can not enable NS 3: Permission denied!
build	25-Jul-2018 00:05:23	2018/07/25 09:03:41 warnings: ZEBRA: Can not associate NS 3 with NETNS /run/netns/r1-cust1
build	25-Jul-2018 00:05:23	2018/07/25 09:03:41 warnings: ZEBRA: NS notify : failed to create NS /run/netns/r1-cust1
build	25-Jul-2018 00:05:23	core_handler: showing active allocations in memory group libfrr
build	25-Jul-2018 00:05:23	core_handler: memstats:  Host config                   :      4 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Command Tokens                :   3375 *         72
build	25-Jul-2018 00:05:23	core_handler: memstats:  Command Token Text            :   2510 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Command Token Help            :   2510 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Command Argument Name         :    620 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Graph                         :     23 *          8
build	25-Jul-2018 00:05:23	core_handler: memstats:  Graph Node                    :   3972 *         32
build	25-Jul-2018 00:05:23	core_handler: memstats:  Hash                          :     86 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Hash Bucket                   :    609 *         32
build	25-Jul-2018 00:05:23	core_handler: memstats:  Hash Index                    :     43 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Hook entry                    :     13 *         48
build	25-Jul-2018 00:05:23	core_handler: memstats:  Link List                     :     13 *         40
build	25-Jul-2018 00:05:23	core_handler: memstats:  Link Node                     :     53 *         24
build	25-Jul-2018 00:05:23	core_handler: memstats:  Logging                       :      2 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Temporary memory              :      1 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  NetNS Context                 :      8 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  NetNS Name                    :      4 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Priority queue                :      1 *         32
build	25-Jul-2018 00:05:23	core_handler: memstats:  Priority queue data           :      1 *        256
build	25-Jul-2018 00:05:23	core_handler: memstats:  Privilege information         :      2 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Stream                        :      3 *         40
build	25-Jul-2018 00:05:23	core_handler: memstats:  Stream data                   :      3 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Route table                   :      3 *         48
build	25-Jul-2018 00:05:23	core_handler: memstats:  Thread                        :     16 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Thread master                 :      3 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Thread stats                  :     12 *         64
build	25-Jul-2018 00:05:23	core_handler: memstats:  Vector                        :   7995 *         16
build	25-Jul-2018 00:05:23	core_handler: memstats:  Vector index                  :   7995 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Work queue                    :      2 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: memstats:  Work queue item               :      1 *         24
build	25-Jul-2018 00:05:23	core_handler: memstats:  Work queue name string        :      1 * (variably sized)
build	25-Jul-2018 00:05:23	core_handler: showing active allocations in memory group Label Manager
build	25-Jul-2018 00:05:23	core_handler: showing active allocations in memory group zebra
build	25-Jul-2018 00:05:23	core_handler: memstats:  Zebra Name Space              :      4 *        312
build	25-Jul-2018 00:05:23	core_handler: showing active allocations in memory group Table Manager
build	25-Jul-2018 00:05:23	
build	25-Jul-2018 00:05:23	PASSED2018-07-25 09:05:23,955 INFO: stopping topology: test_ospf_topo1_vrf
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,963 INFO: stopping "s3"
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,963 INFO: stopping "s2"
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,963 INFO: stopping "s1"
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,963 INFO: stopping "s4"
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,969 INFO: stopping "s3"
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,969 INFO: stopping "s2"
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,970 INFO: stopping "s1"
build	25-Jul-2018 00:05:23	2018-07-25 09:05:23,970 INFO: stopping "s4"
```

( link : https://ci1.netdef.org/browse/FRR-TOPOPR-T5B-288/log )

I can't merge it if it will make PRs fail, would you mind to investigate it? Maybe even disable on `5.0`.

**Comment by rzalamena** [comment]
This last `i386` failure seems to be related with FRR's PR https://github.com/FRRouting/frr/pull/2720 .

I'll wait until that PR is merged to merge this one.

**Comment by pguibert6WIND** [comment]
Hi @rzalamena , when you have time to relaunch PR72 CI, keep me in touch to know if test passes or not without seg core. thanks?

**Pull request merged**
