### PR TITLE
BGP VRF testing

### PR DESCRIPTION
**Pull request by pguibert6WIND**
Hi,

this is the start of a pull request for testing VRF with NETNS backend.
this is not finalised yet.
but at least, this can permit checking with experts on topotests that what is done until now is correct.

### CODE REVIEW

**Comment by pguibert6WIND** [comment]
Hi @mwinter-osr , if you have time to have a look first topotest implementation, you re welcome.

note the specificity of netns configuration in a mininet setup.
( I learnt from https://sreeninet.wordpress.com/2014/11/30/mininet-internals-and-network-namespaces/ to manually create a VRF instance)

**Comment by pguibert6WIND** [comment]
Hi @mwinter-osr ,
I suppose that so that the check passes, #1662 must be merged first, right ?

**Comment by pguibert6WIND** [comment]
hello @mwinter-osr ,

any news about reviewing that issue ?
I have a V2 version for testing vrf across all topotests testing ( https://github.com/pguibert6WIND/topotests/tree/bgp_vrf_to_bgp_vpn-vmerge1-namingvrf ).
but I need to work more on it. Do you know if it is possible to use a parameter in all python scripts so as to decide which kind of vrf backend one will test ?
 
I ready https://docs.pytest.org/en/latest/example/parametrize.html
But I am not sure how to use it.

**Comment by vjardin6WIND** [comment]
@pguibert6WIND 

Regarding,
>  Do you know if it is possible to use a parameter in all python scripts so as to decide
> which kind of vrf backend one will test ?

What's about using a setenv/getenv to switch between both VRF modes with topotest ?

**Comment by pguibert6WIND** [comment]
closing the issue.
moving to https://github.com/FRRouting/topotests/pull/64

**Pull request closed without merging**
