### PR TITLE
Add OSPF Segment Routing tests

### PR DESCRIPTION
**Pull request by odd22**
- Build a topology made of 4 routers: 3 PE connected to a P
 - Segment Routing is activated on all 4 routers with various setting
for the MSD, Global Block and Prefix (with or without NO-PHP flag)
 - 2 tests have been elaborated: the first one check the consistency of the
Segment Routing database on each router compared to a reference and the second
one check that the MPLS FIB has been correctly configured on each router,
again compared to a reference

Signed-off-by: Olivier Dugeon <olivier.dugeon@orange.com>

### CODE REVIEW

**Comment by odd22** [comment]
@mwinter, Why CI failed on armv7 ? Is it always the MPLS kernel detection that failed ? Or is it another problem ? In the last version, I added `tgen.hasmpls` to check that MPLS is available. Does it failed in armv7 ?

**Comment by mwinter-osr** [comment]
@odd22 Arm7 testbeds don't have full MPLS (kernel version ok, but missing a kernel module). It sounds like the check for MPLS fails. Ping me on slack if you want access to a ARM7 system to debug.

**Comment by louberger** [comment]
@mwinter-osr looks the test is doing the right thing for arm7:
08:54:27,479 INFO: MPLS tests will not run (missing mpls-iptunnel kernel module)

**Comment by odd22** [comment]
@louberger Yes. I confirm. I remove the mpls_iptunnel on my Linux box to simulate the same behaviour. Previously, I correctly detect that MPLS is not supported, but didn't skip properly the test which failed. Now, I group in the same place and same way all potential errors in order to skip test if something is wrong. And because my latest patch about json utput is not yet merge, all tests are skipped on all platform ;-)

**Comment by rzalamena** [comment]
The CI system failure is related to the ISIS test. The second one is about OSPF JSON output change on `master`, which only requires a branch rebase. I think there is nothing else to do before the merge.

**Pull request merged**
