### PR TITLE
Working/start logs in per node dirs

### PR DESCRIPTION
**Pull request by louberger**
align with pr #91

### CODE REVIEW

**Comment by louberger** [comment]
What I totally excellent point.!


----------

**Comment by mwinter-osr** [comment]
The latest change breaks the possibility to run a single test.

ie, if I `cd ospf6-topo1/` and then run `./test_ospf6_topo1.py`:

```
Cleanup old Mininet runs
*** Creating network
*** Adding hosts:
2018-05-21 11:33:16,457 INFO: assert skipped at "test_ospf6_topo1/test_router_running": 'PYTEST_CURRENT_TEST'
E2018-05-21 11:33:16,563 INFO: assert skipped at "test_ospf6_topo1/test_ospf6_converged": 'PYTEST_CURRENT_TEST'
E2018-05-21 11:33:16,662 INFO: assert skipped at "test_ospf6_topo1/test_ospfv3_routingTable": 'PYTEST_CURRENT_TEST'
E2018-05-21 11:33:16,770 INFO: assert skipped at "test_ospf6_topo1/test_linux_ipv6_kernel_routingTable": 'PYTEST_CURRENT_TEST'
E2018-05-21 11:33:16,862 INFO: assert skipped at "test_ospf6_topo1/test_shutdown_check_stderr": 'PYTEST_CURRENT_TEST'
E2018-05-21 11:33:16,957 INFO: assert skipped at "test_ospf6_topo1/test_shutdown_check_memleak": 'PYTEST_CURRENT_TEST'
E

============================================================================ ERRORS =============================================================================
_____________________________________________________________ ERROR at setup of test_router_running _____________________________________________________________

[...]
```

**Comment by mwinter-osr** [comment]
Correction: This was an issue with old version of py.test.
I had pytest-3.0.5. It seems to work at pytest-3.4.2. Not sure where this was changed, but we may need to document the version requirement for the topotests

...still testing the PR...

**Comment by louberger** [comment]
Will do...


----------

**Comment by louberger** [comment]
@rzalamena @mwinter-osr requested changes are in!

**Comment by mwinter-osr** [comment]
All good now. Thanks.

**Pull request merged**
