### PR TITLE
BGP ECMP Topology

### PR DESCRIPTION
**Pull request by rzalamena**
This Pull Request adds a new BGP topology to topotest. The topology is very simple, but has a lot of BGP routers to test ECMP and it can be expanded to include more tests later. The main use case of this test is to make sure that BGP multipath works and to cover the modifications in this FRR PR: https://github.com/FRRouting/frr/pull/750

It was also implemented support for list comparison inside of JSON data, along with that the appropriate tests for the function.

### CODE REVIEW

**Comment by donaldsharp** [comment]
Is this waiting on anything in particular?

**Comment by mwinter-osr** [comment]
Yes, I think Rafael has a newer, better version - expecting PR anytime. Think of this PR as a "placeholder" until the other PR is in.

**Comment by mwinter-osr** [comment]
I believe this PR can be closed as the newer version is merged. @rzalamena please close if you agree.

**Comment by donaldsharp** [comment]
If the new version is merged in please close this down I am in agreement with @mwinter-osr

**Pull request closed without merging**
