### PR TITLE
LDP VPLS Topology

### PR DESCRIPTION
**Pull request by rwestphal**

### CODE REVIEW

**Comment by rzalamena** [comment]
Your LDP VPLS topology tests looks very good!

There are just two things that we must fix before merging it:

1. `@pytest.mark.skipif` should not be used to detect run-time errors. That function is only called by `pytest` on initialization, so we can only use it for the information we have on the environment.
2. this topology is failing on frr 2.0 branch, probably because there is no 'json' output commands. We should talk and figure out how to skip these tests on this version.

**Comment by rzalamena** [comment]
I have re-run the tests with log artifacts enabled, so now we can confirm that those 'json' commands don't exist.

These are the missing commands that I found looking at the 'r1' log file:

```
2017-07-14 14:29:07,121 INFO: 
vtysh command => show mpls ldp discovery json
vtysh output <= % Unknown command.

2017-07-14 14:29:07,279 INFO: 
vtysh command => show mpls ldp neighbor json
vtysh output <= % Unknown command.

2017-07-14 14:29:07,357 INFO: 
vtysh command => show mpls ldp binding json
vtysh output <= % Unknown command.

2017-07-14 14:29:07,434 INFO: 
vtysh command => show l2vpn atom binding json
vtysh output <= % Unknown command.

2017-07-14 14:29:07,512 INFO: 
vtysh command => show l2vpn atom vc json
vtysh output <= % Unknown command.

2017-07-14 14:29:22,619 INFO: 
vtysh command => show l2vpn atom vc json
vtysh output <= % Unknown command.
```

**Comment by rwestphal** [comment]
Yes, I was discussing this issue with Martin yesterday. We need to find a way to skip all tests when running on the 2.0 branch. Not only because of these missing commands but also because the pseudowire manager will be merged on 3.0 only. And without the pseudowire manager this topotest is very superficial.

**Comment by mwinter-osr** [comment]
I think one easy/useful way would be to implement some function to extract major/minor version from FRR (from `show version` or from `zebra -v`) command, so we can do a simple skip for tests which require a min FRR version. 
(Or even better, extract `product` (ie `FRRouting`) as well, so check can be for FRRouting and version)

Thoughts?

**Comment by rwestphal** [comment]
@mwinter-osr Yes, I think the `has_version()` function  already does that and is very easy to use. Example: `if router.has_version('<', '3')`

The problem with my PR is a programming error. `router` is undefined in the `setup_module()` function. We need to loop through all routers and call `has_version()` on them all. Rafael suggested implementing this logic in topogen to favor code reuse in the future. I'll take a look at this later.

**Comment by rzalamena** [comment]
I noticed that when we call `pytest.exit()` it aborts all tests, so I changed that bit to make it keep going. With that I found some other problems that we had never met before and fixed them.

Besides that, your code looks good and should go in. I'll merge as soon as we get the CI results back.

**Pull request merged**
